require 'spec_helper'

describe 'yum_test::test_dnf' do
  platform 'redhat', '8'

  let(:test_dnf_run) do
    ChefSpec::SoloRunner.new(
      step_into: 'yum_globalconfig'
    ).converge(described_recipe)
  end

  let(:test_dnf_content) do
    '# This file was generated by Chef Infra Client
# Do NOT modify this file by hand.

[main]
cachedir=/var/cache/yum/$basearch/$releasever
debuglevel=2
exactarch=1
gpgcheck=1
installonly_limit=3
install_weak_deps=1
keepcache=0
localpkg_gpgcheck=0
logfile=/var/log/yum.log
obsoletes=1
plugins=1'
  end

  context 'creating a DNF yum_globalconfig with minimal parameters' do
    it 'creates yum_globalconfig[/tmp/dnf.conf]' do
      expect(test_dnf_run).to create_yum_globalconfig('/tmp/dnf.conf')
    end

    it 'steps into yum_globalconfig and creates template[/tmp/dnf.conf]' do
      expect(test_dnf_run).to create_template('/tmp/dnf.conf')
    end

    it 'steps into yum_globalconfig and renders file[/tmp/dnf.conf]' do
      expect(test_dnf_run).to render_file('/tmp/dnf.conf').with_content(test_dnf_content)
    end
  end
end
